website/src/UserBundle/Entity/Teacher.php
<?php

namespace UserBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass="UserBundle\Entity\Repository\TeacherRepository")
 * @ORM\Table(name="teachers")
 */
class Teacher extends User
{
    /**
     * @var User
     *
     * @ORM\ManyToOne(targetEntity="UserBundle\Entity\User", inversedBy="teachers")
     */
    protected $user;

    /**
     * @ORM\Column(type="boolean", options={"default": false})
     */
    protected $blocked = false;

    /**
     * @return User
     */
    public function getUser()
    {
        return $this->user;
    }

    /**
     * @param User $user
     */
    public function setUser($user)
    {
        $this->user = $user;
    }

    /**
     * @return mixed
     */
    public function getBlocked()
    {
        return $this->blocked;
    }

    /**
     * @param mixed $blocked
     */
    public function setBlocked($blocked)
    {
        $this->blocked = $blocked;
    }

    public function getStorageLimit()
    {
        return $this->getUser()->getStorageLimit();
    }

    public function getPlanStorageLimit()
    {
        return $this->getUser()->getPlanStorageLimit();
    }

    public function getSubdomain()
    {
        return $this->user->getSubdomain();
    }

    public function getReseller()
    {
        return $this->user->getReseller();
    }
}

website/src/UserBundle/Controller/UserController.php
<?php

namespace UserBundle\Controller;

use FOS\UserBundle\Event\GetResponseNullableUserEvent;
use FOS\UserBundle\Event\GetResponseUserEvent;
use FOS\UserBundle\FOSUserEvents;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Symfony\Component\Filesystem\Exception\FileNotFoundException;
use Symfony\Component\Filesystem\Filesystem;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\HttpFoundation\Request;
use UserBundle\Entity\Teacher;
use UserBundle\Entity\User;
use UserBundle\Form\Type\EditEmailType;
use UserBundle\Form\Type\EditLogoType;
use UserBundle\Form\Type\EditNameType;
use Symfony\Component\HttpFoundation\JsonResponse;
use UserBundle\Form\Type\EditPhoneType;
use UserBundle\Form\Type\EditSubdomainType;
use UserBundle\Form\Type\TeacherType;

class UserController extends Controller
{
    /**
     * @Route("/profile", name="user_show_profile")
     */
    public function showProfileAction()
    {
        $user = $this->getUser();
        $filename = $user->getClassroomLogo();
        $user = $this->transformLogoToFile($user);

        $editNameForm = $this->createForm(EditNameType::class, $user);
        $editEmailForm = $this->createForm(EditEmailType::class, $user);
        $editPhoneForm = $this->createForm(EditPhoneType::class, $user);
        $editSubdomainForm = $this->createForm(EditSubdomainType::class, $user);
        $editLogoForm = $this->createForm(EditLogoType::class, $user);
        $subscription = $this->get('stripe.manager')->retrieveSubscriptionFromUser($this->getUser());
        $session = $this->get('session');
        if ($session->get('userStateIsChanged')) {
            $session->set('userStateIsChanged', false);

            $uniqueIdForNewUserState = uniqid();

            return $this->render('UserBundle:User:profile.html.twig', [
                'user' => $user,
                'userLogo' => $filename,
                'editNameForm' => $editNameForm->createView(),
                'editEmailForm' => $editEmailForm->createView(),
                'editPhoneForm' => $editPhoneForm->createView(),
                'editSubdomainForm' => $editSubdomainForm->createView(),
                'editLogoForm' => $editLogoForm->createView(),
                'subscription' => $subscription,
                'uniqueIdForNewUserState' => $uniqueIdForNewUserState,
            ]);
        }

        return $this->render('UserBundle:User:profile.html.twig', [
            'user' => $user,
            'userLogo' => $filename,
            'subscription' => $subscription,
            'editNameForm' => $editNameForm->createView(),
            'editEmailForm' => $editEmailForm->createView(),
            'editPhoneForm' => $editPhoneForm->createView(),
            'editSubdomainForm' => $editSubdomainForm->createView(),
            'editLogoForm' => $editLogoForm->createView(),
        ]);
    }

    /**
     * @Route("/{id}/get-edit-name-form", name="user_get_edit_name_form_ajax", options={"expose"=true})
     */
    public function getEditNameFormAction(User $user)
    {
        $form = $this->createForm(new EditNameType(), $user);

        return new JsonResponse([
            'form' => $this->renderView(
                'UserBundle:User:editName.html.twig', [
                    'editNameForm' => $form->createView(),
                    'user' => $user
                ]
            )
        ]);
    }

    /**
     * @Route("/{id}/get-edit-email-form", name="user_get_edit_email_form_ajax", options={"expose"=true})
     */
    public function getEditEmailFormAction(User $user)
    {
        $form = $this->createForm(new EditEmailType(), $user);

        return new JsonResponse([
            'form' => $this->renderView(
                'UserBundle:User:editEmail.html.twig', [
                    'editEmailForm' => $form->createView(),
                    'user' => $user
                ]
            )
        ]);
    }

    /**
     * @Route("/{id}/get-edit-phone-form", name="user_get_edit_phone_form_ajax", options={"expose"=true})
     */
    public function getEditPhoneFormAction(User $user)
    {
        $form = $this->createForm(new EditPhoneType(), $user);

        return new JsonResponse([
            'form' => $this->renderView(
                'UserBundle:User:editPhone.html.twig', [
                    'editPhoneForm' => $form->createView(),
                    'user' => $user
                ]
            )
        ]);
    }

    /**
     * @param User $user
     *
     * @return JsonResponse
     *
     * @Route(path="/{id}/get-edit-subdomain-form", name="user_get_edit_subdomain_form_ajax", options={"expose"=true})
     */
    public function getEditSubdomainFormAction(User $user)
    {
        $form = $this->createForm(EditSubdomainType::class, $user);

        return new JsonResponse([
            'form' => $this->renderView('UserBundle:User:editSubdomain.html.twig', [
                'editSubdomainForm' => $form->createView(),
                'user' => $user,
            ]),
        ]);
    }

    /**
     * @Route("/{id}/edit-user-name-ajax", name="user_edit_name_ajax", options={"expose"=true})
     */
    public function editNameAction(User $user, Request $request)
    {
        $userName = $user->getName();

        $form = $this->createForm(new EditNameType(), $user);

        $form->handleRequest($request);

        if ($form->isValid() && $request->isXmlHttpRequest()) {
            $userManager = $this->get('fos_user.user_manager');
            $userManager->updateUser($user);

            return new JsonResponse([
                'message' => 'valid',
                'form' => $this->renderView(
                    'UserBundle:User:editName.html.twig', [
                        'editNameForm' => $form->createView(),
                        'user' => $user
                    ]
                )
            ]);
        }

        $user->setName($userName);

        return new JsonResponse([
            'message' => 'invalid',
            'form' => $this->renderView(
                'UserBundle:User:editName.html.twig', [
                    'editNameForm' => $form->createView(),
                    'user' => $user
                ]
            )
        ]);
    }

    /**
     * @Route("/{id}/edit-user-email-ajax", name="user_edit_email_ajax", options={"expose"=true})
     */
    public function editEmailAction(User $user, Request $request)
    {
        $userEmail = $user->getEmail();

        $form = $this->createForm(new EditEmailType(), $user);

        $form->handleRequest($request);

        if ($form->isValid() && $request->isXmlHttpRequest()) {
            $userManager = $this->get('fos_user.user_manager');
            $userManager->updateUser($user);

            return new JsonResponse([
                'message' => 'valid',
                'form' => $this->renderView(
                    'UserBundle:User:editEmail.html.twig', [
                        'editEmailForm' => $form->createView(),
                        'user' => $user
                    ]
                )
            ]);
        }

        $user->setEmail($userEmail);

        return new JsonResponse([
            'message' => 'invalid',
            'form' => $this->renderView(
                'UserBundle:User:editEmail.html.twig', [
                    'editEmailForm' => $form->createView(),
                    'user' => $user
                ]
            )
        ]);
    }

    /**
     * @Route("/{id}/edit-user-phone-ajax", name="user_edit_phone_ajax", options={"expose"=true})
     */
    public function editPhoneAction(User $user, Request $request)
    {
        $userName = $user->getName();

        $form = $this->createForm(new EditPhoneType(), $user);

        $form->handleRequest($request);

        if ($form->get('phone')->isValid()) {
            $this->get('phone_number_validator.util')->validatePhoneNumberLength($form->get('phone'));
        }

        if ($form->isValid() && $request->isXmlHttpRequest()) {
            $userManager = $this->get('fos_user.user_manager');
            $userManager->updateUser($user);

            return new JsonResponse([
                'message' => 'valid',
                'form' => $this->renderView(
                    'UserBundle:User:editPhone.html.twig', [
                        'editPhoneForm' => $form->createView(),
                        'user' => $user
                    ]
                )
            ]);
        }

        $user->setName($userName);

        return new JsonResponse([
            'message' => 'invalid',
            'form' => $this->renderView(
                'UserBundle:User:editPhone.html.twig', [
                    'editPhoneForm' => $form->createView(),
                    'user' => $user
                ]
            )
        ]);
    }

    /**
     * @param User    $user
     * @param Request $request
     *
     * @return JsonResponse
     *
     * @Route(path="/{id}/edit-user-subdomain-ajax", name="user_edit_subdomain_ajax", options={"expose"=true})
     */
    public function editSubdomainAction(User $user, Request $request)
    {
        $subdomain = $user->getSubdomain();

        $form = $this->createForm(EditSubdomainType::class, $user);

        $form->handleRequest($request);
        $message = 'invalid';
        if ($form->isValid() && $request->isXmlHttpRequest()) {
            $userManager = $this->get('fos_user.user_manager');
            $userManager->updateUser($user);
            $message = 'valid';
        } else {
            $user->setSubdomain($subdomain);
        }

        return new JsonResponse([
            'message' => $message,
            'form' => $this->renderView('UserBundle:User:editSubdomain.html.twig', [
                'editSubdomainForm' => $form->createView(),
                'user' => $user,
            ]),
        ]);
    }

    /**

website/src/UserBundle/Resources/views/User/addTeacher.html.twig
{% form_theme form 'bootstrap_3_layout.html.twig' %}

{{ form_start(form) }}
{{ form_row(form.email) }}
{{ form_row(form.name) }}
{{ form_row(form.phone) }}
{{ form_errors(form) }}
<div class="modal-buttons text-center">
    <button class="btn learnium-default-btn" data-dismiss="modal">Cancel</button>
    &nbsp;&nbsp;&nbsp;&nbsp;
    &nbsp;&nbsp;&nbsp;&nbsp;
    <button class="add-teacher-button btn learnium-info-btn">Add</button>
</div>
{{ form_end(form) }}

website/src/UserBundle/Resources/views/User/deleteTeacherForm.html.twig
<input class="teacher-id-for-deleting" type="hidden">
<p>Are you sure you want to delete this teacher?</p>
<div class="modal-buttons text-center">
    <button class="btn learnium-default-btn" data-dismiss="modal">No</button>
    &nbsp;&nbsp;&nbsp;&nbsp;
    &nbsp;&nbsp;&nbsp;&nbsp;
    <button class="delete-teacher-button btn learnium-danger-btn">Yes</button>
</div>

website/src/UserBundle/Resources/views/User/editEmail.html.twig
{% form_theme editEmailForm 'bootstrap_3_layout.html.twig' %}


<div class="email-form profile-form-block">
    {{ form_start(editEmailForm) }}
    <div class="form-group {{ editEmailForm.email.vars.errors|length > 0 ? 'has-error' : '' }}">
        <label class="profile-label">
            Email
        </label>

        <div class="view-field-block">
            <span class="profile-field">{{ user.email }}</span>
        <span class="edit-email-button edit-button glyphicon glyphicon-pencil"
              data-href="{{ path('user_get_edit_email_form_ajax', {id: user.id}) }}"></span>
        </div>
        <div class="edit-field-block">
            {{ form_widget(editEmailForm.email) }}
            <div class="field-actions">
                <span class="save-email-button save-button glyphicon learning-ok"
                      data-href="{{ path('user_edit_email_ajax', {id: editEmailForm.vars.value.id}) }}"></span>
                <span class="cancel-button glyphicon learning-remove"></span>
            </div>
            {{ form_errors(editEmailForm.email) }}
        </div>
    </div>
    {{ form_end(editEmailForm) }}
</div>

website/src/UserBundle/Resources/views/User/editLogo.html.twig
{% form_theme editLogoForm 'bootstrap_3_layout.html.twig' %}

<div class="logo-form profile-form-block">
    {{ form_start(editLogoForm, {attr:{id:'edit-logo-form'}}) }}
    <div class="form-group {{ editLogoForm.classroomLogo.vars.errors|length > 0 ? 'has-error' : '' }}">
        <label class="profile-label">
            Logo
        </label>

        <div class="logo-container">
            {% if user.classroomLogo %}
                <img src="{{ asset('uploads/logo/' ~ userLogo) }}" class="logo"/>
            {% else %}
                {% if logo %}
                    <img src="{{ logo }}" class="logo"/>
                {% else %}
                    {% image '@UserBundle/Resources/public/images/logo-default.jpg' %}
                        <img src="{{ asset_url }}" class="logo">
                    {% endimage %}
                {% endif %}
            {% endif %}
            <div class="preloader sk-fading-circle hidden">
                <div class="sk-circle1 sk-circle"></div>
                <div class="sk-circle2 sk-circle"></div>
                <div class="sk-circle3 sk-circle"></div>
                <div class="sk-circle4 sk-circle"></div>
                <div class="sk-circle5 sk-circle"></div>
                <div class="sk-circle6 sk-circle"></div>
                <div class="sk-circle7 sk-circle"></div>
                <div class="sk-circle8 sk-circle"></div>
                <div class="sk-circle9 sk-circle"></div>
                <div class="sk-circle10 sk-circle"></div>
                <div class="sk-circle11 sk-circle"></div>
                <div class="sk-circle12 sk-circle"></div>
            </div>
        </div>
        <div class="field-errors {% if editLogoForm.classroomLogo.vars.errors|length == 0 %}hidden{% endif %}">
            <span class="help-block">
                <ul class="list-unstyled">
                    <li>
                        <span class="glyphicon glyphicon-exclamation-sign"></span> Please, upload image in supported format: .jpg, .png
                    </li>
                </ul>
            </span>
        </div>
        <div class="logo-actions">
            <div class="save-logo-button"
                 data-href="{{ path('user_edit_logo_ajax', {id: user.id}) }}">Upload
            </div>
            {% if user.classroomLogo %}
                <div class="delete-logo-button"
                     data-href="{{ path('user_delete_logo_ajax', {id: user.id}) }}"></div>
            {% endif %}
        </div>
        <div class="edit-field-block">
            {{ form_widget(editLogoForm.classroomLogo) }}
        </div>
        <div class="logo-note">
            Supported formats: .jpg, .png
        </div>
    </div>
    {{ form_end(editLogoForm) }}
</div>

website/src/UserBundle/Resources/views/User/editName.html.twig
{% form_theme editNameForm 'bootstrap_3_layout.html.twig' %}

<div class="username-form profile-form-block">
    {{ form_start(editNameForm) }}
    <div class="form-group {{ editNameForm.name.vars.errors|length > 0 ? 'has-error' : '' }}">
        <label class="profile-label">
            Name
        </label>

        <div class="view-field-block">
            <span class="profile-field">{{ user.name }}</span>
        <span class="edit-name-button edit-button glyphicon glyphicon-pencil"
              data-href="{{ path('user_get_edit_name_form_ajax', {id: user.id}) }}"></span>
        </div>
        <div class="edit-field-block">
            {{ form_widget(editNameForm.name) }}
            <div class="field-actions">
                <span class="save-name-button save-button glyphicon learning-ok"
                      data-href="{{ path('user_edit_name_ajax', {id: user.id}) }}"></span>
                <span class="cancel-button glyphicon learning-remove"></span>
            </div>
            {{ form_errors(editNameForm.name) }}
        </div>
    </div>
    {{ form_end(editNameForm) }}
</div>

website/src/UserBundle/Resources/views/User/editPhone.html.twig
{% form_theme editPhoneForm 'bootstrap_3_layout.html.twig' %}

<div class="phone-form profile-form-block">
    {{ form_start(editPhoneForm) }}
    <div class="form-group {{ editPhoneForm.phone.vars.errors|length > 0 ? 'has-error' : '' }}">
        <label class="profile-label">
            Phone number
        </label>

        <div class="view-field-block">
            <span class="profile-field">{{ user.phone|phone_number_format() }}</span>
            <span class="edit-phone-button edit-button glyphicon glyphicon-pencil"
                  data-href="{{ path('user_get_edit_phone_form_ajax', {id: user.id}) }}"></span>
        </div>
        <div class="edit-field-block">
            {{ form_widget(editPhoneForm.phone) }}
            <div class="field-actions">
                <span class="save-phone-button save-button glyphicon learning-ok"
                      data-href="{{ path('user_edit_phone_ajax', {id: user.id}) }}"></span>
                <span class="cancel-button glyphicon learning-remove"></span>
            </div>
            {{ form_errors(editPhoneForm.phone) }}
        </div>
    </div>
    {{ form_end(editPhoneForm) }}
</div>

website/src/UserBundle/Resources/views/User/editSubdomain.html.twig
{% form_theme editSubdomainForm 'bootstrap_3_layout.html.twig' %}

<div class="subdomain-form profile-form-block">
    {{ form_start(editSubdomainForm) }}
    <div class="form-group {{ editSubdomainForm.subdomain.vars.errors|length > 0 ? 'has-error' : '' }}">
        <label class="profile-label">
            Subdomain
        </label>

        <div class="view-field-block">
            <span class="profile-field">{{ user.subdomain ?: '---' }}</span>
            <span class="edit-subdomain-button edit-button glyphicon glyphicon-pencil"
                  data-href="{{ path('user_get_edit_subdomain_form_ajax', {id: user.id}) }}"></span>
        </div>
        <div class="edit-field-block">
            {{ form_widget(editSubdomainForm.subdomain) }}
            <div class="field-actions">
                <span class="save-subdomain-button save-button glyphicon learning-ok"
                      data-href="{{ path('user_edit_subdomain_ajax', {id: user.id}) }}"></span>
                <span class="cancel-button glyphicon learning-remove"></span>
            </div>
            {{ form_errors(editSubdomainForm.subdomain) }}
        </div>
    </div>
    {{ form_end(editSubdomainForm) }}
</div>

website/src/UserBundle/Resources/views/User/editTeacher.html.twig
{% form_theme form 'bootstrap_3_layout.html.twig' %}

{{ form_start(form, {'attr': {'class': 'edit-teacher-form'}}) }}
    {{ form_row(form.email) }}
    {{ form_row(form.name) }}
    {{ form_row(form.phone) }}
    <input class="teacher-id-for-editing" type="hidden" value="{{ teacher.id }}">

<div class="modal-buttons text-center">
    <button class="btn learnium-default-btn" data-dismiss="modal">Cancel</button>
    &nbsp;&nbsp;&nbsp;&nbsp;
    &nbsp;&nbsp;&nbsp;&nbsp;
    <button class="edit-teacher-button btn learnium-secondary-btn">Edit</button>
</div>
{{ form_end(form) }}

website/src/UserBundle/Resources/views/User/profile.html.twig
{% extends 'UserBundle::layout.html.twig' %}

{% block title %}My profile{% endblock %}

{% block stylesheets %}
    {{ parent() }}

    {% stylesheets filter='?uglifycss'
        '@UserBundle/Resources/public/less/profile.less' %}
        <link rel="stylesheet" href="{{ asset_url }}">
    {% endstylesheets %}
{% endblock %}

{% block content %}
    <div class="edit-forms">
        {% include 'UserBundle:User:editName.html.twig' %}
        {% include 'UserBundle:User:editEmail.html.twig' %}
    </div>

    <div class="profile-form-block">
        <label class="profile-label">
            Password
        </label>
        <span class="profile-field">**********</span>
        <span class="change-password-button glyphicon glyphicon-pencil"></span>
    </div>

    <div class="edit-forms">
        {% include 'UserBundle:User:editPhone.html.twig' %}
        {% if (not app.user.reseller or app.user.reseller.isAllowSubdomains) and is_granted('ROLE_TEACHER') %}
            {% include 'UserBundle:User:editSubdomain.html.twig' %}
        {% endif %}
    </div>

    {% if is_granted('ROLE_TEACHER') and (app.user.plan and app.user.plan.name != 'Basic') %}
        <div class="edit-forms" id="logo-form-block">
            {% include 'UserBundle:User:editLogo.html.twig' %}
        </div>
    {% endif %}

    {# <p>Current subscription plan: {{ app.user.plan.name }}</p> #}
    <div class="modal fade" id="changePasswordModal" tabindex="-1" role="dialog"
         aria-labelledby="changePasswordModalLabel" aria-hidden="true" data-keyboard="false" data-backdrop="static">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <h4 class="modal-title" id="changePasswordModalLabel">Change password</h4>
                </div>
                <div class="modal-body">

                </div>
            </div>
        </div>
    </div>
{% endblock %}

    {% block javascript %}
        {{ parent() }}

        <script src="{{ asset('bundles/fosjsrouting/js/router.js') }}"></script>
        <script src="{{ path('fos_js_routing_js', { callback: 'fos.Router.setData' }) }}"></script>

        {% javascripts filter='?uglifyjs2'
            '@UserBundle/Resources/public/js/profile.js'
            '@UserBundle/Resources/public/js/uploadLogo.js' %}
            <script src="{{ asset_url }}"></script>
        {% endjavascripts %}
    {% endblock %}

website/src/UserBundle/Resources/views/User/teachers.html.twig
{% extends 'UserBundle::layout.html.twig' %}

{% block title %}Teachers{% endblock %}

{% block stylesheets %}
    {{ parent() }}

    {% stylesheets filter='?uglifycss'
    '@UserBundle/Resources/public/less/teachers.less'
    %}
    <link rel="stylesheet" href="{{ asset_url }}">
    {% endstylesheets %}
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-xs-12">
            <div class="teachers-table-row row">
                {% include 'UserBundle:User:teachersTable.html.twig' %}
            </div>
        </div>
    </div>


    <div class="modal fade" id="addTeacherModal" tabindex="-1" role="dialog" aria-labelledby="addTeacherModalLabel" aria-hidden="true" data-keyboard="false" data-backdrop="static">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <h4 class="modal-title" id="addTeacherModalLabel">Add teacher</h4>
                </div>
                <div class="modal-body">
                    {% include 'UserBundle:User:addTeacher.html.twig' %}
                </div>
            </div>
        </div>
    </div>

    <div class="modal fade" id="deleteTeacherModal" tabindex="-1" role="dialog" aria-labelledby="deleteTeacherModalLabel" aria-hidden="true" data-keyboard="false" data-backdrop="static">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <h4 class="modal-title" id="deleteTeacherModalLabel">Delete teacher?</h4>
                </div>
                <div class="modal-body">

                </div>
            </div>
        </div>
    </div>

    <div class="modal fade" id="editTeacherModal" tabindex="-1" role="dialog" aria-labelledby="editTeacherModalLabel" aria-hidden="true" data-keyboard="false" data-backdrop="static">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <h4 class="modal-title" id="editTeacherModalLabel">Edit teacher</h4>
                </div>
                <div class="modal-body">

                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block javascript %}
    {{ parent() }}

    <script src="{{ asset('bundles/fosjsrouting/js/router.js') }}"></script>
    <script src="{{ path('fos_js_routing_js', { callback: 'fos.Router.setData' }) }}"></script>

    {% javascripts filter='?uglifyjs2'
    '@UserBundle/Resources/public/js/teachers.js'
    %}
    <script src="{{ asset_url }}"></script>
    {% endjavascripts %}
{%  endblock %}

website/src/UserBundle/Resources/views/User/teachersTable.html.twig
{% if app.user.teachers|length < app.user.numberOfTeachers - 1 %}
    <div class="add-button-block col-xs-12">
        <button class="get-add-teacher-modal-button btn learnium-primary-btn">Add teacher</button>
    </div>
{% endif %}

<div class="teachers-table-block col-xs-12">
    {% if app.user.teachers|length != 0 and app.user.numberOfTeachers != 0 %}
        <table class="teachers-table table">
            <tr>
                <th>Name</th>
                <th>Email</th>
                <th>Phone</th>
                <th>Status</th>
                <th></th>
            </tr>
            {% for teacher in app.user.teachers %}
                <tr class="teacher-row" data-user-id="{{ teacher.id }}">
                    <td>{{ teacher.name }}</td>
                    <td>{{ teacher.email }}</td>
                    <td>{{ teacher.phone|phone_number_format() }}</td>
                    <td>
                        {% if teacher.blocked == false %}
                            Active
                        {% else %}
                            Blocked
                        {% endif %}
                    </td>
                    <td>
                        <input class="teacher-id" type="hidden" value="{{ teacher.id }}">
                        <a class="show-edit-teacher-modal-button action-link" href="#">
                            <img src="{{ asset('bundles/app/images/icons/edit.png') }}" class="edit-icon">
                            <img src="{{ asset('bundles/app/images/icons/edit-hover.png') }}" class="hover-edit-icon">
                        </a>
                        <a class="show-delete-teacher-modal-button action-link" href="#">
                            <img src="{{ asset('bundles/app/images/icons/delete.png') }}" class="delete-icon">
                            <img src="{{ asset('bundles/app/images/icons/delete-hover.png') }}"
                                 class="hover-delete-icon">
                        </a>
                        {% if not is_granted('ROLE_PREVIOUS_ADMIN') and 'ROLE_SUB_TEACHER' in teacher.roles and teacher.enabled and not teacher.blocked %}
                            <a class="btn learnium-success-btn btn action-link"
                               href="{{ path('homepage', {'_switch_user':teacher.username}) }}" data-toggle="modal">Login
                                as</a>
                        {% else %}
                            <a class="btn learnium-success-btn btn invisible action-link"
                               href="{{ path('homepage', {'_switch_user':teacher.username}) }}" data-toggle="modal">Login
                                as</a>
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
        </table>
    {% elseif app.user.numberOfTeachers == 1 %}
        <p class="alert alert-info info-message">You can't add teachers on your current subscription</p>
    {% else %}
        <p class="alert alert-info info-message">You haven't any teachers</p>
    {% endif %}
</div>